/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eldodev.gui;

import com.eldodev.dao.ConexaoBD;
import com.eldodev.dao.VendaDAO;
import com.eldodev.gui.to.VendaTableModel;
import com.eldodev.modelo.Venda;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Teck Trakker
 */

public class CadastroVendas extends javax.swing.JFrame {

    private Menu menu;
    
    /**
     * Creates new form CadastroVendas
     * @param menu
     */
    public CadastroVendas(Menu menu) {
        this.menu = menu;
        // ... inicialização da interface do usuário ...
    }
    public CadastroVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jTextCliente = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jformPreco = new javax.swing.JFormattedTextField();
        jformAno = new javax.swing.JFormattedTextField();
        jTextCor = new javax.swing.JTextField();
        jTextModelo = new javax.swing.JTextField();
        jTextVeiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btNovo1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setName("desktopPane"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanelFormulario.add(jTextCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 240, 30));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 76), 2));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanelFormulario.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 70, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Limpar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 76), 2));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanelFormulario.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 80, -1));

        jformPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        jPanelFormulario.add(jformPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 180, 30));

        jformAno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        jformAno.setCaretColor(new java.awt.Color(255, 0, 0));
        jformAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformAnoActionPerformed(evt);
            }
        });
        jPanelFormulario.add(jformAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 180, 30));

        jTextCor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanelFormulario.add(jTextCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 240, 30));

        jTextModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanelFormulario.add(jTextModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 240, 30));

        jTextVeiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanelFormulario.add(jTextVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome do Cliente:");
        jPanelFormulario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Veiculo:");
        jPanelFormulario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Modelo:");
        jPanelFormulario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cor:");
        jPanelFormulario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 30, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Ano de Fabrico:");
        jPanelFormulario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Preço de Venda:");
        jPanelFormulario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        btNovo1.setBackground(new java.awt.Color(255, 255, 255));
        btNovo1.setText("Novo");
        btNovo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 76), 2));
        btNovo1.setFocusable(false);
        btNovo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btNovo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo1ActionPerformed(evt);
            }
        });
        jPanelFormulario.add(btNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informe os detalhes da venda!");
        jPanelFormulario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jPanelFormulario.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 380, 10));

        jPanel1.add(jPanelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 0, 430, 520));

        jPanel2.setBackground(new java.awt.Color(0, 0, 76));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVisualizar.setBackground(new java.awt.Color(0, 0, 76));
        btnVisualizar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eldodev/gui/img/finalizar.png"))); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.setActionCommand("   Visualizar   ");
        btnVisualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVisualizar.setBorderPainted(false);
        btnVisualizar.setContentAreaFilled(false);
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
    Menu menu = null;
        try {
            menu = new Menu();
        } catch (Exception ex) {
            Logger.getLogger(CadastroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    // Chama o método visualizarDados da instância menu
    menu.visualizarDados();

    // Torna a interface Menu visível
    menu.setVisible(true);
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo1ActionPerformed
        limparCampos();
        jTextCliente.requestFocus();
        jPanelFormulario.setVisible(true);
    }//GEN-LAST:event_btNovo1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Venda venda = new Venda();
        

        // Obtém os valores dos campos de texto
        String cliente = jTextCliente.getText();
        String cor = jTextCor.getText();
        String modelo = jTextModelo.getText();
        String veiculo = jTextVeiculo.getText();
        String anoFabricoText = jformAno.getText();
        String precoText = jformPreco.getText();

        // Verifica se algum campo obrigatório está vazio
        if (cliente.isEmpty() || cor.isEmpty() || modelo.isEmpty() || veiculo.isEmpty() || anoFabricoText.isEmpty() || precoText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de salvar.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

    try {
            // Define os valores na instância de Venda
            venda.setCliente(cliente);
            venda.setCor(cor);
            venda.setModelo(modelo);
            venda.setVeiculo(veiculo);
            venda.setAnoFabrico(Double.parseDouble(anoFabricoText));
            venda.setPreco(Double.parseDouble(precoText));
        } catch (NumberFormatException e) {
            // Exibe uma mensagem de erro se o usuário não inserir um número válido
            JOptionPane.showMessageDialog(this, "Erro ao converter o ano de fabricação ou o preço para Double.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
        // Tenta inserir a venda no banco de dados
        try (Connection conexao = ConexaoBD.conectar()) {
            VendaDAO vendaDAO = new VendaDAO(conexao);
            vendaDAO.inserir(venda);

            // Limpa os campos de texto
            limparCampos();

            // Verifica se 'menu' foi inicializado antes de chamar o método
            if (menu != null) {
                // Atualiza os dados na tabela tbGrade1
                menu.visualizarDados();
            } else {
                System.err.println("A instância 'Menu' foi inicializada.");
            }

            // Exibe uma mensagem de sucesso
            JOptionPane.showMessageDialog(this, "Dados guardados com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            // Exibe uma mensagem de erro se houver um problema ao conectar ou inserir no banco de dados
            JOptionPane.showMessageDialog(this, "Erro ao guardar dados no banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        // Adicione um bloco catch mais amplo para lidar com exceções
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jformAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jformAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextCor;
    private javax.swing.JTextField jTextModelo;
    private javax.swing.JTextField jTextVeiculo;
    private javax.swing.JFormattedTextField jformAno;
    private javax.swing.JFormattedTextField jformPreco;
    // End of variables declaration//GEN-END:variables
private void limparCampos() {
        jTextCliente.setText("");
        jTextCor.setText("");
        jTextModelo.setText("");
        jTextVeiculo.setText("");
        jformAno.setText("");
        jformPreco.setText("");
    }

    private void visualizarDados() {
        try (Connection conexao = ConexaoBD.conectar()) {
            // Cria uma nova instância de VendaDAO
            VendaDAO vendaDAO = new VendaDAO(conexao);

            // Recupera todas as vendas do banco de dados
            List<Venda> vendas = vendaDAO.listarTodos();

            // Cria uma nova instância de VendaTableModel e define os dados
            VendaTableModel vendaTableModel = new VendaTableModel();
            vendaTableModel.setDados(vendas);

            // Define o modelo da sua tabela para o VendaTableModel
        } catch (SQLException e) {
            // Trata o erro se houver um problema ao conectar ou listar do banco de dados
            System.out.println("Erro ao visualizar dados do banco de dados.");
            e.printStackTrace();
        }
    }
}

