/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eldodev.gui;
import com.eldodev.dao.ConexaoBD;
import com.eldodev.dao.VendaDAO;
import com.eldodev.gui.to.VendaTableModel;
import com.eldodev.modelo.Venda;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Teck Trakker
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     * @throws java.lang.Exception
     */
    
    public Menu() throws Exception {
        initComponents();
        VendaTableModel vendaTableModel = new VendaTableModel();
        tbGrade1.setModel(vendaTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConteudo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btncadastrar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tpConteudo1 = new javax.swing.JTabbedPane();
        jpnCadastrar = new javax.swing.JPanel();
        spGrade1 = new javax.swing.JScrollPane();
        tbGrade1 = new javax.swing.JTable();
        jPanelTabela = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btNovo1 = new javax.swing.JButton();
        pnBarraFerramentas1 = new javax.swing.JPanel();
        barraFerramentas1 = new javax.swing.JToolBar();
        btExcluir1 = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        spGrade = new javax.swing.JScrollPane();
        tbGrade = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(54, 33, 89));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelConteudo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelConteudo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncadastrar.setBackground(new java.awt.Color(54, 33, 89));
        btncadastrar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        btncadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btncadastrar.setText("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 30));

        btnRelatorio.setBackground(new java.awt.Color(54, 33, 89));
        btnRelatorio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setText("Visualizar");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        jPanel2.add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 30));

        jButton1.setBackground(new java.awt.Color(54, 33, 89));
        jButton1.setFont(new java.awt.Font("Vogue ExtraBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eldodev/gui/img/sair.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 60, -1));

        jPanelConteudo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 590));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 51));
        jPanelConteudo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 720, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Cadastro de Vendas de Veiculos");
        jPanelConteudo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 400, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpConteudo1.setToolTipText("Cadastrar Venda");

        jpnCadastrar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 0)));
        jpnCadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbGrade1.setBackground(new java.awt.Color(54, 33, 89));
        tbGrade1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        tbGrade1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbGrade1.setForeground(new java.awt.Color(255, 255, 255));
        tbGrade1.setModel(new VendaTableModel());
        tbGrade1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGrade1MouseClicked(evt);
            }
        });
        spGrade1.setViewportView(tbGrade1);

        jpnCadastrar.add(spGrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 420));

        tpConteudo1.addTab("Cadastros Finalizados", jpnCadastrar);

        jPanelTabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        jPanelTabela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btNovo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eldodev/gui/img/novo.png"))); // NOI18N
        btNovo1.setText("Novo");
        btNovo1.setFocusable(false);
        btNovo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btNovo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo1ActionPerformed(evt);
            }
        });
        jPanel7.add(btNovo1);

        pnBarraFerramentas1.setOpaque(false);
        pnBarraFerramentas1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        barraFerramentas1.setFloatable(false);

        btExcluir1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        btExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eldodev/gui/img/excluir.png"))); // NOI18N
        btExcluir1.setText("Excluir");
        btExcluir1.setFocusable(false);
        btExcluir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btExcluir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btExcluir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluir1ActionPerformed(evt);
            }
        });
        barraFerramentas1.add(btExcluir1);

        btEditar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eldodev/gui/img/cancelar.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setFocusable(false);
        btEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEditar.setMargin(new java.awt.Insets(2, 8, 2, 8));
        btEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        barraFerramentas1.add(btEditar);

        pnBarraFerramentas1.add(barraFerramentas1);

        jPanel7.add(pnBarraFerramentas1);
        jPanel7.add(jPanel8);

        jPanelTabela.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 380, 60));

        tbGrade.setBackground(new java.awt.Color(0, 0, 76));
        tbGrade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 2));
        tbGrade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbGrade.setForeground(new java.awt.Color(255, 255, 255));
        tbGrade.setModel(new VendaTableModel());
        tbGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGradeMouseClicked(evt);
            }
        });
        spGrade.setViewportView(tbGrade);

        jPanelTabela.add(spGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 700, 350));

        tpConteudo1.addTab("Editar Registos", jPanelTabela);

        jPanel3.add(tpConteudo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));
        tpConteudo1.getAccessibleContext().setAccessibleName("Cadastrar Venda");

        jPanelConteudo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 720, 460));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tela de cadastrar e gerenciar todas as transações de vendas!");
        jPanelConteudo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 580, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eldodev/gui/img/carro.png"))); // NOI18N
        jPanelConteudo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        getContentPane().add(jPanelConteudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        CadastroVendas v = new CadastroVendas();
        v.setVisible(true);

    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        visualizarDados();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
            // Obtenha a linha e a coluna selecionadas
        int linhaSelecionada = tbGrade.getSelectedRow();
        int colunaSelecionada = tbGrade.getSelectedColumn();

        // Verifique se uma célula foi selecionada
        if (linhaSelecionada != -1 && colunaSelecionada != -1) {
            // Obtenha o modelo da tabela e a venda na linha selecionada
            VendaTableModel vendaTableModel = (VendaTableModel) tbGrade.getModel();
            Venda venda = vendaTableModel.getRowValue(linhaSelecionada);

            // Obtenha o valor atual da célula selecionada
            Object valorAtual = vendaTableModel.getValueAt(linhaSelecionada, colunaSelecionada);

            // Peça ao usuário para inserir um novo valor
            String novoValor = JOptionPane.showInputDialog(this, "Insira um novo valor para " + vendaTableModel.getColumnName(colunaSelecionada) + ":", valorAtual);

            // Se o usuário pressionar "Cancelar" ou fechar a caixa de diálogo, não faça nada
            if (novoValor == null) {
                return;
            }

            // Pergunta de confirmação
            int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente salvar as alterações?", "Confirmação", JOptionPane.YES_NO_OPTION);

            // Verifica se o usuário escolheu "Sim" (YES_OPTION)
            if (opcao == JOptionPane.YES_OPTION) {
                // Atualize o valor da célula selecionada com o novo valor
                // Aqui você precisará adicionar o código para atualizar o valor na instância de Venda e no banco de dados
                switch (colunaSelecionada) {
                    case 0:
                        venda.setCliente(novoValor);
                        break;
                    case 1:
                        venda.setVeiculo(novoValor);
                        break;
                    case 2:
                        venda.setModelo(novoValor);
                        break;
                    case 3:
                        venda.setCor(novoValor);
                        break;
                    case 4:
                        venda.setPreco(Double.parseDouble(novoValor));
                        break;
                    case 5:
                        venda.setAnoFabrico(Double.parseDouble(novoValor));
                        break;
                }

                try (Connection conexao = ConexaoBD.conectar()) {
                    // Crie uma nova instância de VendaDAO e atualize a venda
                    VendaDAO vendaDAO = new VendaDAO(conexao);
                    vendaDAO.alterar(venda);

                    // Atualize a tabela com os dados mais recentes do banco de dados
                    List<Venda> vendas = vendaDAO.listarTodos();
                    vendaTableModel.setDados(vendas);

                    // Exiba uma mensagem de sucesso
                    JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    // Exiba uma mensagem de erro se houver um problema ao conectar ou atualizar no banco de dados
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar dados no banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // Exiba uma mensagem se nenhuma célula foi selecionada
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma célula para editar.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluir1ActionPerformed
        // TODO add your handling code here:
    int linhaSelecionada = tbGrade.getSelectedRow();

    // Verifique se uma linha foi selecionada
    if (linhaSelecionada != -1) {
        // Pergunta de confirmação
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir os dados selecionados?", "Confirmação", JOptionPane.YES_NO_OPTION);

        // Verifica se o usuário escolheu "Sim" (YES_OPTION)
        if (opcao == JOptionPane.YES_OPTION) {
            // Obtenha o modelo da tabela e a venda na linha selecionada
            VendaTableModel vendaTableModel = (VendaTableModel) tbGrade.getModel();
            Venda venda = vendaTableModel.getRowValue(linhaSelecionada);

            try (Connection conexao = ConexaoBD.conectar()) {
                // Crie uma nova instância de VendaDAO e exclua a venda
                VendaDAO vendaDAO = new VendaDAO(conexao);
                vendaDAO.excluir(venda);

                // Remova a venda da tabela e atualize a tabela
                vendaTableModel.fireTableRowsDeleted(linhaSelecionada, linhaSelecionada);

                // Atualize a tabela com os dados mais recentes do banco de dados
                List<Venda> vendas = vendaDAO.listarTodos();
                vendaTableModel.setDados(vendas);

                // Exiba uma mensagem de sucesso
                JOptionPane.showMessageDialog(this, "Dados excluídos com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                // Exiba uma mensagem de erro se houver um problema ao conectar ou excluir do banco de dados
                JOptionPane.showMessageDialog(this, "Erro ao excluir dados do banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        // Exiba uma mensagem se nenhuma linha foi selecionada
        JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btExcluir1ActionPerformed

    private void tbGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGradeMouseClicked

    }//GEN-LAST:event_tbGradeMouseClicked

    private void btNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo1ActionPerformed
        CadastroVendas v = new CadastroVendas();
        v.setVisible(true);
   
    }//GEN-LAST:event_btNovo1ActionPerformed

    private void tbGrade1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGrade1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbGrade1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Menu().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraFerramentas1;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir1;
    private javax.swing.JButton btNovo1;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelConteudo;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpnCadastrar;
    private javax.swing.JPanel pnBarraFerramentas1;
    private javax.swing.JScrollPane spGrade;
    private javax.swing.JScrollPane spGrade1;
    private javax.swing.JTable tbGrade;
    private javax.swing.JTable tbGrade1;
    private javax.swing.JTabbedPane tpConteudo1;
    // End of variables declaration//GEN-END:variables

    void visualizarDados() {
    try (Connection conexao = ConexaoBD.conectar()) {
            // Cria uma nova instância de VendaDAO
            VendaDAO vendaDAO = new VendaDAO(conexao);

            // Recupera todas as vendas do banco de dados
            List<Venda> vendas = vendaDAO.listarTodos();

            // Cria uma nova instância de VendaTableModel e define os dados
            VendaTableModel vendaTableModel = new VendaTableModel();
            vendaTableModel.setDados(vendas);

            // Define o modelo da sua tabela para o VendaTableModel
            tbGrade1.setModel(vendaTableModel);
            tbGrade.setModel(vendaTableModel);
        } catch (SQLException e) {
            // Trata o erro se houver um problema ao conectar ou listar do banco de dados
            System.out.println("Erro ao visualizar dados do banco de dados.");
        }
    }
    
    
}

